version: '3.8'

services:
  app:
    build:
      target: development
    volumes:
      - ./app:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
