FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

# Install wget and netcat-openbsd
RUN apt-get update && apt-get install -y wget netcat-openbsd

# Download and install wait-for v2.2.3 from eficode/wait-for repository
RUN wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for > /usr/local/bin/wait-for \
    && chmod +x /usr/local/bin/wait-for
